const List<Map<String, dynamic>> kLocalSurahData = [
  {'number': 1, 'arName': 'الفاتحة', 'nameEn': 'Al-Faatiha', 'type': 'Meccan', 'ayatCount': 7},
  {'number': 2, 'arName': 'البقرة', 'nameEn': 'Al-Baqara', 'type': 'Medinan', 'ayatCount': 286},
  {'number': 3, 'arName': 'آل عمران', 'nameEn': 'Aal-i-Imraan', 'type': 'Medinan', 'ayatCount': 200},
  {'number': 4, 'arName': 'النساء', 'nameEn': 'An-Nisaa', 'type': 'Medinan', 'ayatCount': 176},
  {'number': 5, 'arName': 'المائدة', 'nameEn': 'Al-Maaida', 'type': 'Medinan', 'ayatCount': 120},
  {'number': 6, 'arName': 'الأنعام', 'nameEn': 'Al-An\'aam', 'type': 'Meccan', 'ayatCount': 165},
  {'number': 7, 'arName': 'الأعراف', 'nameEn': 'Al-A\'raaf', 'type': 'Meccan', 'ayatCount': 206},
  {'number': 8, 'arName': 'الأنفال', 'nameEn': 'Al-Anfaal', 'type': 'Medinan', 'ayatCount': 75},
  {'number': 9, 'arName': 'التوبة', 'nameEn': 'At-Tawba', 'type': 'Medinan', 'ayatCount': 139},
  {'number': 10, 'arName': 'يونس', 'nameEn': 'Yunus', 'type': 'Meccan', 'ayatCount': 109},
  {'number': 11, 'arName': 'هود', 'nameEn': 'Hud', 'type': 'Meccan', 'ayatCount': 123},
  {'number': 12, 'arName': 'يوسف', 'nameEn': 'Yusuf', 'type': 'Meccan', 'ayatCount': 111},
  {'number': 13, 'arName': 'الرعد', 'nameEn': 'Ar-Ra\'d', 'type': 'Medinan', 'ayatCount': 43},
  {'number': 14, 'arName': 'إبراهيم', 'nameEn': 'Ibrahim', 'type': 'Meccan', 'ayatCount': 52},
  {'number': 15, 'arName': 'الحجر', 'nameEn': 'Al-Hijr', 'type': 'Meccan', 'ayatCount': 99},
  {'number': 16, 'arName': 'النحل', 'nameEn': 'An-Nahl', 'type': 'Meccan', 'ayatCount': 128},
  {'number': 17, 'arName': 'الإسراء', 'nameEn': 'Al-Israa', 'type': 'Meccan', 'ayatCount': 111},
  {'number': 18, 'arName': 'الكهف', 'nameEn': 'Al-Kahf', 'type': 'Meccan', 'ayatCount': 110},
  {'number': 19, 'arName': 'مريم', 'nameEn': 'Maryam', 'type': 'Meccan', 'ayatCount': 98},
  {'number': 20, 'arName': 'طه', 'nameEn': 'Taa-Haa', 'type': 'Meccan', 'ayatCount': 135},
  {'number': 21, 'arName': 'الأنبياء', 'nameEn': 'Al-Anbiyaa', 'type': 'Meccan', 'ayatCount': 112},
  {'number': 22, 'arName': 'الحج', 'nameEn': 'Al-Hajj', 'type': 'Medinan', 'ayatCount': 78},
  {'number': 23, 'arName': 'المؤمنون', 'nameEn': 'Al-Muminoon', 'type': 'Meccan', 'ayatCount': 118},
  {'number': 24, 'arName': 'النور', 'nameEn': 'An-Noor', 'type': 'Medinan', 'ayatCount': 64},
  {'number': 25, 'arName': 'الفرقان', 'nameEn': 'Al-Furqaan', 'type': 'Meccan', 'ayatCount': 77},
  {'number': 26, 'arName': 'الشعراء', 'nameEn': 'Ash-Shu\'araa', 'type': 'Meccan', 'ayatCount': 227},
  {'number': 27, 'arName': 'النمل', 'nameEn': 'An-Naml', 'type': 'Meccan', 'ayatCount': 93},
  {'number': 28, 'arName': 'القصص', 'nameEn': 'Al-Qasas', 'type': 'Meccan', 'ayatCount': 88},
  {'number': 29, 'arName': 'العنكبوت', 'nameEn': 'Al-Ankaboot', 'type': 'Meccan', 'ayatCount': 69},
  {'number': 30, 'arName': 'الروم', 'nameEn': 'Ar-Room', 'type': 'Meccan', 'ayatCount': 60},
  {'number': 31, 'arName': 'لقمان', 'nameEn': 'Luqman', 'type': 'Meccan', 'ayatCount': 34},
  {'number': 32, 'arName': 'السجدة', 'nameEn': 'As-Sajda', 'type': 'Meccan', 'ayatCount': 30},
  {'number': 33, 'arName': 'الأحزاب', 'nameEn': 'Al-Ahzaab', 'type': 'Medinan', 'ayatCount': 73},
  {'number': 34, 'arName': 'سبأ', 'nameEn': 'Saba', 'type': 'Meccan', 'ayatCount': 54},
  {'number': 35, 'arName': 'فاطر', 'nameEn': 'Faatir', 'type': 'Meccan', 'ayatCount': 45},
  {'number': 36, 'arName': 'يس', 'nameEn': 'Yaseen', 'type': 'Meccan', 'ayatCount': 83},
  {'number': 37, 'arName': 'الصافات', 'nameEn': 'As-Saaffaat', 'type': 'Meccan', 'ayatCount': 182},
  {'number': 38, 'arName': 'ص', 'nameEn': 'Saad', 'type': 'Meccan', 'ayatCount': 88},
  {'number': 39, 'arName': 'الزمر', 'nameEn': 'Az-Zumar', 'type': 'Meccan', 'ayatCount': 75},
  {'number': 40, 'arName': 'غافر', 'nameEn': 'Ghafir', 'type': 'Meccan', 'ayatCount': 85},
  {'number': 41, 'arName': 'فصلت', 'nameEn': 'Fussilat', 'type': 'Meccan', 'ayatCount': 54},
  {'number': 42, 'arName': 'الشورى', 'nameEn': 'Ash-Shura', 'type': 'Meccan', 'ayatCount': 53},
  {'number': 43, 'arName': 'الزخرف', 'nameEn': 'Az-Zukhruf', 'type': 'Meccan', 'ayatCount': 89},
  {'number': 44, 'arName': 'الدخان', 'nameEn': 'Ad-Dukhaan', 'type': 'Meccan', 'ayatCount': 59},
  {'number': 45, 'arName': 'الجاثية', 'nameEn': 'Al-Jaathiya', 'type': 'Meccan', 'ayatCount': 37},
  {'number': 46, 'arName': 'الأحقاف', 'nameEn': 'Al-Ahqaf', 'type': 'Meccan', 'ayatCount': 35},
  {'number': 47, 'arName': 'محمد', 'nameEn': 'Muhammad', 'type': 'Medinan', 'ayatCount': 38},
  {'number': 48, 'arName': 'الفتح', 'nameEn': 'Al-Fath', 'type': 'Medinan', 'ayatCount': 29},
  {'number': 49, 'arName': 'الحجرات', 'nameEn': 'Al-Hujuraat', 'type': 'Medinan', 'ayatCount': 18},
  {'number': 50, 'arName': 'ق', 'nameEn': 'Qaaf', 'type': 'Meccan', 'ayatCount': 45},
  {'number': 51, 'arName': 'الذاريات', 'nameEn': 'Adh-Dhaariyat', 'type': 'Meccan', 'ayatCount': 60},
  {'number': 52, 'arName': 'الطور', 'nameEn': 'At-Tur', 'type': 'Meccan', 'ayatCount': 49},
  {'number': 53, 'arName': 'النجم', 'nameEn': 'An-Najm', 'type': 'Meccan', 'ayatCount': 62},
  {'number': 54, 'arName': 'القمر', 'nameEn': 'Al-Qamar', 'type': 'Meccan', 'ayatCount': 55},
  {'number': 55, 'arName': 'الرحمن', 'nameEn': 'Ar-Rahmaan', 'type': 'Medinan', 'ayatCount': 78},
  {'number': 56, 'arName': 'الواقعة', 'nameEn': 'Al-Waaqia', 'type': 'Meccan', 'ayatCount': 96},
  {'number': 57, 'arName': 'الحديد', 'nameEn': 'Al-Hadid', 'type': 'Medinan', 'ayatCount': 29},
  {'number': 58, 'arName': 'المجادلة', 'nameEn': 'Al-Mujaadila', 'type': 'Medinan', 'ayatCount': 22},
  {'number': 59, 'arName': 'الحشر', 'nameEn': 'Al-Hashr', 'type': 'Medinan', 'ayatCount': 24},
  {'number': 60, 'arName': 'الممتحنة', 'nameEn': 'Al-Mumtahana', 'type': 'Medinan', 'ayatCount': 13},
  {'number': 61, 'arName': 'الصف', 'nameEn': 'As-Saff', 'type': 'Medinan', 'ayatCount': 14},
  {'number': 62, 'arName': 'الجمعة', 'nameEn': 'Al-Jumu\'a', 'type': 'Medinan', 'ayatCount': 11},
  {'number': 63, 'arName': 'المنافقون', 'nameEn': 'Al-Munaafiqoon', 'type': 'Medinan', 'ayatCount': 11},
  {'number': 64, 'arName': 'التغابن', 'nameEn': 'At-Taghaabun', 'type': 'Medinan', 'ayatCount': 18},
  {'number': 65, 'arName': 'الطلاق', 'nameEn': 'At-Talaaq', 'type': 'Medinan', 'ayatCount': 12},
  {'number': 66, 'arName': 'التحريم', 'nameEn': 'At-Tahrim', 'type': 'Medinan', 'ayatCount': 12},
  {'number': 67, 'arName': 'الملك', 'nameEn': 'Al-Mulk', 'type': 'Meccan', 'ayatCount': 30},
  {'number': 68, 'arName': 'القلم', 'nameEn': 'Al-Qalam', 'type': 'Meccan', 'ayatCount': 52},
  {'number': 69, 'arName': 'الحاقة', 'nameEn': 'Al-Haaqqa', 'type': 'Meccan', 'ayatCount': 52},
  {'number': 70, 'arName': 'المعارج', 'nameEn': 'Al-Ma\'aarij', 'type': 'Meccan', 'ayatCount': 44},
  {'number': 71, 'arName': 'نوح', 'nameEn': 'Nooh', 'type': 'Meccan', 'ayatCount': 28},
  {'number': 72, 'arName': 'الجن', 'nameEn': 'Al-Jinn', 'type': 'Meccan', 'ayatCount': 28},
  {'number': 73, 'arName': 'المزمل', 'nameEn': 'Al-Muzzammil', 'type': 'Meccan', 'ayatCount': 20},
  {'number': 74, 'arName': 'المدثر', 'nameEn': 'Al-Muddaththir', 'type': 'Meccan', 'ayatCount': 56},
  {'number': 75, 'arName': 'القيامة', 'nameEn': 'Al-Qiyaama', 'type': 'Meccan', 'ayatCount': 40},
  {'number': 76, 'arName': 'الإنسان', 'nameEn': 'Al-Insaan', 'type': 'Medinan', 'ayatCount': 31},
  {'number': 77, 'arName': 'المرسلات', 'nameEn': 'Al-Mursalaat', 'type': 'Meccan', 'ayatCount': 50},
  {'number': 78, 'arName': 'النبأ', 'nameEn': 'An-Naba', 'type': 'Meccan', 'ayatCount': 40},
  {'number': 79, 'arName': 'النازعات', 'nameEn': 'An-Naazi\'aat', 'type': 'Meccan', 'ayatCount': 46},
  {'number': 80, 'arName': 'عبس', 'nameEn': 'Abasa', 'type': 'Meccan', 'ayatCount': 42},
  {'number': 81, 'arName': 'التكوير', 'nameEn': 'At-Takwir', 'type': 'Meccan', 'ayatCount': 29},
  {'number': 82, 'arName': 'الانفطار', 'nameEn': 'Al-Infitaar', 'type': 'Meccan', 'ayatCount': 19},
  {'number': 83, 'arName': 'المطففين', 'nameEn': 'Al-Mutaffifin', 'type': 'Meccan', 'ayatCount': 36},
  {'number': 84, 'arName': 'الانشقاق', 'nameEn': 'Al-Inshiqaaq', 'type': 'Meccan', 'ayatCount': 25},
  {'number': 85, 'arName': 'البروج', 'nameEn': 'Al-Burooj', 'type': 'Meccan', 'ayatCount': 22},
  {'number': 86, 'arName': 'الطارق', 'nameEn': 'At-Taariq', 'type': 'Meccan', 'ayatCount': 17},
  {'number': 87, 'arName': 'الأعلى', 'nameEn': 'Al-A\'laa', 'type': 'Meccan', 'ayatCount': 19},
  {'number': 88, 'arName': 'الغاشية', 'nameEn': 'Al-Ghaashiya', 'type': 'Meccan', 'ayatCount': 26},
  {'number': 89, 'arName': 'الفجر', 'nameEn': 'Al-Fajr', 'type': 'Meccan', 'ayatCount': 30},
  {'number': 90, 'arName': 'البلد', 'nameEn': 'Al-Balad', 'type': 'Meccan', 'ayatCount': 20},
  {'number': 91, 'arName': 'الشمس', 'nameEn': 'Ash-Shams', 'type': 'Meccan', 'ayatCount': 15},
  {'number': 92, 'arName': 'الليل', 'nameEn': 'Al-Lail', 'type': 'Meccan', 'ayatCount': 21},
  {'number': 93, 'arName': 'الضحى', 'nameEn': 'Ad-Dhuhaa', 'type': 'Meccan', 'ayatCount': 11},
  {'number': 94, 'arName': 'الشرح', 'nameEn': 'Ash-Sharh', 'type': 'Meccan', 'ayatCount': 8},
  {'number': 95, 'arName': 'التين', 'nameEn': 'At-Tin', 'type': 'Meccan', 'ayatCount': 8},
  {'number': 96, 'arName': 'العلق', 'nameEn': 'Al-Alaq', 'type': 'Meccan', 'ayatCount': 19},
  {'number': 97, 'arName': 'القدر', 'nameEn': 'Al-Qadr', 'type': 'Meccan', 'ayatCount': 5},
  {'number': 98, 'arName': 'البينة', 'nameEn': 'Al-Bayyina', 'type': 'Medinan', 'ayatCount': 8},
  {'number': 99, 'arName': 'الزلزلة', 'nameEn': 'Az-Zalzala', 'type': 'Medinan', 'ayatCount': 8},
  {'number': 100, 'arName': 'العاديات', 'nameEn': 'Al-Aadiyaat', 'type': 'Meccan', 'ayatCount': 11},
  {'number': 101, 'arName': 'القارعة', 'nameEn': 'Al-Qaari\'a', 'type': 'Meccan', 'ayatCount': 11},
  {'number': 102, 'arName': 'التكاثر', 'nameEn': 'At-Takaathur', 'type': 'Meccan', 'ayatCount': 8},
  {'number': 103, 'arName': 'العصر', 'nameEn': 'Al-Asr', 'type': 'Meccan', 'ayatCount': 3},
  {'number': 104, 'arName': 'الهمزة', 'nameEn': 'Al-Humaza', 'type': 'Meccan', 'ayatCount': 9},
  {'number': 105, 'arName': 'الفيل', 'nameEn': 'Al-Fil', 'type': 'Meccan', 'ayatCount': 5},
  {'number': 106, 'arName': 'قريش', 'nameEn': 'Quraish', 'type': 'Meccan', 'ayatCount': 4},
  {'number': 107, 'arName': 'الماعون', 'nameEn': 'Al-Maa\'un', 'type': 'Meccan', 'ayatCount': 7},
  {'number': 108, 'arName': 'الكوثر', 'nameEn': 'Al-Kawthar', 'type': 'Meccan', 'ayatCount': 3},
  {'number': 109, 'arName': 'الكافرون', 'nameEn': 'Al-Kaafiroon', 'type': 'Meccan', 'ayatCount': 6},
  {'number': 110, 'arName': 'النصر', 'nameEn': 'An-Nasr', 'type': 'Medinan', 'ayatCount': 3},
  {'number': 111, 'arName': 'المسد', 'nameEn': 'Al-Masad', 'type': 'Meccan', 'ayatCount': 5},
  {'number': 112, 'arName': 'الإخلاص', 'nameEn': 'Al-Ikhlaas', 'type': 'Meccan', 'ayatCount': 4},
  {'number': 113, 'arName': 'الفلق', 'nameEn': 'Al-Falaq', 'type': 'Meccan', 'ayatCount': 5},
  {'number': 114, 'arName': 'الناس', 'nameEn': 'An-Naas', 'type': 'Meccan', 'ayatCount': 6},
];

const List<String> kPlainSurahNames = [
  'الفاتحة',
  'البقرة',
  'آل عمران',
  'النساء',
  'المائدة',
  'الأنعام',
  'الأعراف',
  'الأنفال',
  'التوبة',
  'يونس',
  'هود',
  'يوسف',
  'الرعد',
  'إبراهيم',
  'الحجر',
  'النحل',
  'الإسراء',
  'الكهف',
  'مريم',
  'طه',
  'الأنبياء',
  'الحج',
  'المؤمنون',
  'النور',
  'الفرقان',
  'الشعراء',
  'النمل',
  'القصص',
  'العنكبوت',
  'الروم',
  'لقمان',
  'السجدة',
  'الأحزاب',
  'سبأ',
  'فاطر',
  'يس',
  'الصافات',
  'ص',
  'الزمر',
  'غافر',
  'فصلت',
  'الشورى',
  'الزخرف',
  'الدخان',
  'الجاثية',
  'الأحقاف',
  'محمد',
  'الفتح',
  'الحجرات',
  'ق',
  'الذاريات',
  'الطور',
  'النجم',
  'القمر',
  'الرحمن',
  'الواقعة',
  'الحديد',
  'المجادلة',
  'الحشر',
  'الممتحنة',
  'الصف',
  'الجمعة',
  'المنافقون',
  'التغابن',
  'الطلاق',
  'التحريم',
  'الملك',
  'القلم',
  'الحاقة',
  'المعارج',
  'نوح',
  'الجن',
  'المزمل',
  'المدثر',
  'القيامة',
  'الإنسان',
  'المرسلات',
  'النبأ',
  'النازعات',
  'عبس',
  'التكوير',
  'الانفطار',
  'المطففين',
  'الانشقاق',
  'البروج',
  'الطارق',
  'الأعلى',
  'الغاشية',
  'الفجر',
  'البلد',
  'الشمس',
  'الليل',
  'الضحى',
  'الشرح',
  'التين',
  'العلق',
  'القدر',
  'البينة',
  'الزلزلة',
  'العاديات',
  'القارعة',
  'التكاثر',
  'العصر',
  'الهمزة',
  'الفيل',
  'قريش',
  'الماعون',
  'الكوثر',
  'الكافرون',
  'النصر',
  'المسد',
  'الإخلاص',
  'الفلق',
  'الناس',
];
